# Generated by Django 2.2.7 on 2019-11-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20191129_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
