# Generated by Django 2.2.7 on 2019-11-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20191129_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/avatar.png', upload_to='profile_pics/'),
        ),
    ]
