# Generated by Django 2.2.7 on 2019-11-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('category', models.CharField(choices=[('police', 'Police Department'), ('health', 'Health & Sanitary Department')], max_length=100)),
                ('contacts', models.CharField(max_length=240)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_services', to='hood.Hood')),
            ],
        ),
    ]
