# Generated by Django 2.2.7 on 2019-12-01 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
