# Generated by Django 2.2.7 on 2019-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_post_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='contacts',
            field=models.CharField(default='addcontacts', max_length=240),
        ),
    ]
