# Generated by Django 2.2.7 on 2019-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_business_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contacts',
            field=models.CharField(default='', max_length=240),
        ),
    ]
