# Generated by Django 2.2.7 on 2019-12-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_auto_20191201_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.CharField(max_length=100),
        ),
    ]
