# Generated by Django 2.2.7 on 2019-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0012_auto_20191202_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hood',
            field=models.CharField(max_length=100),
        ),
    ]
